
// TYPE ARTISAN

export const  REACT_APP_GET_ARTISAN = "GET_ARTISAN"
export const  REACT_APP_POST_ARTISAN = "POST_ARTISAN"
export const  REACT_APP_DELETE_ARTISAN = "DELETE_ARTISAN"
export const  REACT_APP_GET_ARTISAN_FAILED ="GET_ARTISAN_FAILED"
export const  REACT_APP_UPDATE_ARTISAN = "UPDATE_ARTISAN"