
// TYPE ARTISAN

export const  REACT_APP_GET_ARTISAN = "GET_ARTISAN"
export const  REACT_APP_POST_ARTISAN = "POST_ARTISAN"
export const  REACT_APP_DELETE_ARTISAN = "DELETE_ARTISAN"
export const  REACT_APP_GET_ARTISAN_FAILED ="GET_ARTISAN_FAILED"
export const  REACT_APP_UPDATE_ARTISAN = "UPDATE_ARTISAN"


// TYPE CLIENT

export const  REACT_APP_GET_CLIENT = "GET_CLIENT"
export const  REACT_APP_POST_CLIENT= "POST_CLIENT"
export const  REACT_APP_DELETE_CLIENT= "DELETE_CLIENT"
export const  REACT_APP_GET_CLIENT_FAILED ="GET_CLIENT_FAILED"
export const  REACT_APP_UPDATE_CLIENT = "UPDATE_CLIENT"


// type user

export const GET_USER = "GET_USER";
export const UPLOAD_PICTURE = "UPLOAD_PICTURE";
export const UPDATE_BIO = "UPDATE_BIO";
export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const GET_USER_ERRORS = "GET_USER_ERRORS";